### ISSUE TITLE
Ceedling 0.32: "support paths" causing plugin to get stuck.

### ISSUE THREAD

**Issue by tyler-macinnis** [deltalejo/cppcheck-ceedling-plugin#4]
I found another "error", but it's something that only partially affects me. With the new `:paths:` changes in Ceedling 0.32, locations that I define in `:support:` seem to result in cppcheck getting stuck at `Creating Cppcheck xml report...` . It only partially affects me though because for my project I am able to just move the `:support:` paths to `:include:` and it doesn't get stuck. I can't share many details of the project I'm working on so the most explanation I can give is that this:

```yaml
:paths:
  :test:
    - +:test/**
    - -:support
  :source:
    - ../Lib/**
  :include:
    - ../Lib/**
    - ../Startup/**
    - ../Src/**
    - ../Inc/**
    - ../Drivers/CMSIS/**
  :support:
    - support
    - ../Drivers/STM32G0xx_HAL_Driver/Inc/**
  :libraries: []
```

doesn't work and causes it to get stuck. However this:

```yaml
:paths:
  :test:
    - +:test/**
    - -:support
  :source:
    - ../Lib/**
  :include:
    - ../Lib/**
    - ../Startup/**
    - ../Src/**
    - ../Inc/**
    - ../Drivers/CMSIS/**
    - ../Drivers/STM32G0xx_HAL_Driver/Inc/**
  :support:
    - support
  :libraries: []
```

works just fine.

In case it is relevant, I want to also note that I'm using CppCheck in WSL, installing it via snap, then downloading the cppcheck-htmlreport separately to my `/usr/local/bin`.

```bash
#!/bin/bash

# Set noninteractive to avoid prompts during installation
export DEBIAN_FRONTEND=noninteractive

CPPCHECK_HTMLREPORT_INSTALL_DIR="/usr/local/bin"

# Install CppCheck
sudo snap install cppcheck
sudo curl -o "$CPPCHECK_HTMLREPORT_INSTALL_DIR/cppcheck-htmlreport" "https://raw.githubusercontent.com/danmar/cppcheck/main/htmlreport/cppcheck-htmlreport"
sudo chmod +x "$CPPCHECK_HTMLREPORT_INSTALL_DIR/cppcheck-htmlreport"
```

**Comment by deltalejo** [comment]
Are you able to provide the output when running the task? e.g.: `ceedling --verbosity=obnoxious cppcheck:all`
Or at least the `> Shell executed command` part.

**Comment by tyler-macinnis** [comment]
```
 *  Executing task: ceedling --mixin=cppcheck.yml --verbosity=obnoxious cppcheck:all 

🚧 Loaded project configuration at default location using ./project.yml
 + Merging command line mixin using cppcheck.yml
 > Set which Ceedling from config :project ↳ :which_ceedling => gem

Ceedling set up completed in 343 milliseconds
mkdir -p build/gcov/out
mkdir -p build/gcov/results
mkdir -p build/gcov/dependencies
mkdir -p build/artifacts/gcov
mkdir -p build/artifacts/cppcheck
Creating Cppcheck xml report...
```

**Comment by deltalejo** [comment]
Doesn't seem so helpful, I cannot see the actual command executed. Does it freeze also when creating only the text report?

**Comment by tyler-macinnis** [comment]
Yes

**Comment by deltalejo** [comment]
Let me know if you are able to setup a simple project that reproduce the issue.

**Comment by tyler-macinnis** [comment]
The issue may actually be something on my end that I've figured out, let me investigate some then I'll touch back if it isn't, and close the issue if it is.

**Comment by tyler-macinnis** [comment]
When it get an HTML report, it has the following which might be related

![image](https://github.com/deltalejo/ceedling-cppcheck-plugin/assets/21990225/329af1f9-56cd-4f34-8c37-a7bd94612721)

I know you have "includes", but how would I exclude that file?

**Comment by deltalejo** [comment]
Maybe with [substractive paths](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/CeedlingPacket.md#subtractive-paths-entries) can help.

**Comment by tyler-macinnis** [comment]
It looks like the issue is due to a particular very large source file that is just causing cppcheck to freeze. I can tell because if I remove the file, then I'm able to get the results I expect. If I try to run with that file, it's `.a1` file never generates.

**Comment by tyler-macinnis** [comment]
I should note this file was so large I had to split its tests into multiple files and use `CMOCK_MEM_DYNAMIC`

**Comment by tyler-macinnis** [comment]
If there's a way to use options to `-i` to have cppcheck ignore a particular file, that would be very helpful.

**Comment by deltalejo** [comment]
So, maybe Cppcheck is not freezing at all but just working hard on analyzing that large file. Does the file have a lot of preprocessor directives?

**Comment by deltalejo** [comment]
Do you think that adding the `:exclude` section to the configuration options would be helpful? In the mean time, you can specify manually the `-i` option on the `:options` sections. e.g.:

```yaml
:cppcheck:
  :options:
    - -i problematic_file.c
```

**Comment by tyler-macinnis** [comment]
The amount of time it's taking seems more like a freeze. I'll try excluding it tomorrow in the meantime so that the static analysis can at least finish.

**Comment by deltalejo** [comment]
It is also worth checking if running the analysis outside Ceedling with just that file works or also hangs. e.g.:

```shell
cppcheck problematic_file.c
```

**Comment by tyler-macinnis** [comment]
The file does have a lot of preprocessor directives (or at least its header does), but it still seem like an actual freeze. Specifying the `-i` manually though does allow me to get expected static analysis results though so I'll do that in the meantime as a fix.

It's just odd to me because I ran this file with the plugin with Ceedling 0.31 and it worked just fine.

**Comment by deltalejo** [comment]
Maybe with current Ceedling the file is not included in the analysis but with the development version it is included because some changes on `:paths` handling as you pointed out. If you do need to analyze that file, maybe adding the relevant defines and/or undefines to the plugin configuration may help reduce the analysis time as Cppcheck by default test all possible combinations.

**Comment by tyler-macinnis** [comment]
> It is also worth checking if running the analysis outside Ceedling with just that file works or also hangs. e.g.:
> 
> ```shell
> cppcheck problematic_file.c
> ```

It can do this, but when running with the plugin/ceedling it seems like its never going to finish and even using regular cppcheck takes a LONG time. I'm just going to ignore it for now. For the `README.md`, might want to show how you can ignore a file, just in case someone else runs into a similar situation.

**Comment by deltalejo** [comment]
And what about analyzing only that file with the plugin? e.g.: `ceedling cppcheck:problematic_file`. I expect this to take as long as with cppcheck alone.
It is worth noticing that analyzing the whole project enables all checks, so if that file per se takes a long time, combined with the rest of source files, all checks enabled and the fact that the file has a lot of preprocessor macros, the complexity blows up, so it can be expected that the whole project analysis takes a really long time.

**Comment by deltalejo** [comment]
I've just added the config option to exclude files from the analysis, give it a try. Also, if you still want to get the big file analyzed, try setting the check level to *normal*, that may help reducing the analysis time. e.g.:

```yaml
:cppcheck:
  :check_level: normal
```

**Comment by tyler-macinnis** [comment]
The exclude does seem to work.

Running just that file alone with `ceedling cppcheck` also works. Running `all` with the `check_level` at `normal` does allow it to finish too. 

In summary, running on my local machine.

| Check Level | File Excluded | Approx. Time |
|:-----------:|:-------------:|:------------:|
| Normal      | Y             | < 1s         |
| Normal      | N             | 2m 50s       |
| Exhaustive  | Y             | 35s          |
| Exhaustive  | N             |      11m 1.77s        |


This is ran as part of a CI/CD pipeline, so that's why I'm trying to not make it take any longer than it needs to.

I guess the questions I have now are:
- What is the differences between `normal` and `exhaustive` check levels?
- Why this particular file takes so long still and if there's anything I can do to make it take less.

For now, I'll just use a `check_level` of `normal` and no exclusions and see if the pipeline still finishes with that.

**Comment by tyler-macinnis** [comment]
Looking at the [Cppcheck Philosophy](https://github.com/danmar/cppcheck/blob/main/philosophy.md), it might be best to have a `normal` `check_level` be the default.

**Comment by tyler-macinnis** [comment]
Regardless, it does actually finish it seems. It just takes a really long time and with the pipeline machine's capabilities, `exhaustive` results in too long. This can be closed now unless there's any further changes you want to make that I could test.

**Comment by deltalejo** [comment]
Actually, _normal_ check level is Cppcheck's default, I don't remember why I set _exhaustive_ as the default for the plugin. That needs to be changed for sure.
I'm wondering if the big file is from yours or from a publicy available SDK.

**Comment by tyler-macinnis** [comment]
It is not publicly available. However, I do notice now that when running with `check_level` of `normal` I do get the following message in the html report.

> Limiting ValueFlow analysis in function 'XX' since it is too complex. Please specify --check-level=exhaustive to perform full analysis.

The function in question (now that I know the cause), does have a lot of `if` and `switch-case`, which is likely the cause. I believe it's something that can be handled just by writing the function better.

**Comment by tyler-macinnis** [comment]
I think the best thing to do is set the default to `normal`, then close the issue because the rest of the issue (the function in question) is something on my end to solve. Thank you!

**Comment by tyler-macinnis** [comment]
Looking further into this, part of the issue is definitely the snap package. Manually building the latest cppcheck runs MUCH faster.

**Comment by deltalejo** [comment]
@tyler-macinnis
I updated the _main_ branch with a few changes for Ceedling development version. Those include setting the check level to Cppcheck's default (_normal_).

**Comment by tyler-macinnis** [comment]
When I set `:check_level: exhaustive` I get this

```
Ceedling set up completed in 88 milliseconds

🧨 EXCEPTION: undefined local variable or method `check_level' for #<Cppcheck:0x0000555b2a666ea0>
🌱 Ceedling could not complete operations because of errors

Running Raw Tests Output Report
-------------------------------
Tests produced no extra console output.
```

However, this works just fine:

```yaml
:arguments:
    - --check-level=exhaustive
```

I think the error is here:
```ruby
unless @config[:check_level].nil? || @config[:check_level].empty?
      args << "--check-level=#{check_level}"
    end
```

and it needs to be
```ruby
unless @config[:check_level].nil? || @config[:check_level].empty?
      args << "--check-level=#{@config[:check_level]}"
    end
```

**Comment by deltalejo** [comment]
Sorry about that, I've already fixed it.
